import { Column, Entity, Index, PrimaryColumn } from 'typeorm';

/**
 * TypeORM persistence model for the `audit_events` table — one immutable row per
 * recorded event in the append-only, hash-chained log (DESIGN §10 / App. C).
 *
 * Pure data shape: no behavior, no domain types. The mapper translates between
 * this and the AuditEvent entity so the domain never imports TypeORM.
 *
 * `seq` is the chain position (a BIGSERIAL assigned by the DB on insert); it is
 * the PRIMARY KEY and the total order the hash chain links over. `id` is the
 * event's stable UUID (the idempotency key) with its own unique index.
 *
 * The table is append-only: a DB trigger (see the migration) rejects UPDATE and
 * DELETE, so there is no version column and no optimistic concurrency — the only
 * write is an INSERT.
 */
@Entity({ name: 'audit_events' })
export class AuditEventOrmEntity {
  // bigserial; generated by the DB on insert. Read back to learn the assigned seq.
  @PrimaryColumn({ type: 'bigint', generated: 'increment' })
  public seq!: string;

  @Index('uq_audit_events_id', { unique: true })
  @Column({ type: 'uuid' })
  public id!: string;

  @Column({ name: 'tenant_id', type: 'uuid' })
  public tenantId!: string;

  @Column({ type: 'varchar', length: 255 })
  public actor!: string;

  @Column({ type: 'varchar', length: 255 })
  public action!: string;

  @Column({ type: 'varchar', length: 20 })
  public decision!: string;

  @Column({ name: 'resource_kind', type: 'varchar', length: 255 })
  public resourceKind!: string;

  @Column({ name: 'resource_id', type: 'varchar', length: 255 })
  public resourceId!: string;

  @Column({ type: 'varchar', length: 1024, nullable: true })
  public reason!: string | null;

  @Column({ type: 'varchar', length: 512, nullable: true })
  public policy!: string | null;

  @Column({ name: 'decision_id', type: 'varchar', length: 255, nullable: true })
  public decisionId!: string | null;

  @Column({ name: 'trace_id', type: 'varchar', length: 255, nullable: true })
  public traceId!: string | null;

  @Column({ name: 'occurred_at', type: 'timestamptz' })
  public occurredAt!: Date;

  @Column({ name: 'recorded_at', type: 'timestamptz' })
  public recordedAt!: Date;

  @Column({ name: 'prev_hash', type: 'char', length: 64 })
  public prevHash!: string;

  @Index('uq_audit_events_record_hash', { unique: true })
  @Column({ name: 'record_hash', type: 'char', length: 64 })
  public recordHash!: string;
}
