import { mkdir, rename, writeFile } from 'node:fs/promises';
import { isAbsolute, join, resolve } from 'node:path';

import { Injectable, Logger } from '@nestjs/common';
import { dump as yamlDump } from 'js-yaml';

import { type CerbosPolicyDocument } from '@contracts/core';

import { ConfigService } from '../../../../config/config.service';
import { type Policy } from '../../domain/policy.entity';
import { type PolicyPublisher } from '../../application/ports/policy-publisher.port';
import { type CerbosPolicyFile, mapPolicyToCerbosFiles } from './cerbos-policy-mapper';

/** Generated-file banner so an operator never confuses these with hand-authored YAML. */
const GENERATED_BANNER = [
  '# GENERATED by authz-admin (PAP) — DO NOT EDIT BY HAND.',
  '# Compiled from a published Policy version (DB jsonb) and written into the Cerbos',
  '# disk-storage dir, which hot-reloads it (watchForChanges) — DESIGN §3.4, §8.7.',
  '',
].join('\n');

/**
 * Filesystem CerbosPolicyPublisher (DESIGN §3.4, §8.7, FR-8). Compiles a published
 * Policy version into Cerbos `resourcePolicy` YAML (via the pure mapper + the
 * shared `compilePolicyToCerbos`) and writes it — plus any required ancestor-scope
 * passthrough stubs — into the shared `CERBOS_POLICY_DIR`. The PDP watches that dir
 * (`watchForChanges`), so a runtime, user-defined policy becomes effective within
 * seconds with NO restart and NOTHING hardcoded.
 *
 * Writes are atomic per file (temp file + rename) so the PDP never observes a
 * half-written document mid-reload. Fail-closed: any write error propagates so the
 * calling use-case surfaces it rather than leaving the DB and PDP divergent (D8).
 */
@Injectable()
export class FsCerbosPolicyPublisher implements PolicyPublisher {
  private readonly logger = new Logger(FsCerbosPolicyPublisher.name);
  private readonly policyDir: string;

  constructor(config: ConfigService) {
    const configured = config.values.CERBOS_POLICY_DIR;
    // Relative dirs resolve against the process cwd (the repo root in dev /
    // compose), so `deploy/cerbos/policies` lands in the bind-mounted volume.
    this.policyDir = isAbsolute(configured) ? configured : resolve(process.cwd(), configured);
  }

  public async publish(policy: Policy): Promise<void> {
    const files = mapPolicyToCerbosFiles({
      rule: policy.rule,
      scope: policy.scope.toString(),
      policyId: policy.id.toString(),
      version: policy.version,
    });

    await mkdir(this.policyDir, { recursive: true });
    for (const file of files) {
      await this.writeFileAtomic(file);
    }

    this.logger.log(
      `Published policy ${policy.id.toString()} (scope "${policy.scope.toString()}" v${String(
        policy.version,
      )}) -> ${String(files.length)} Cerbos file(s) in ${this.policyDir}`,
    );
  }

  private async writeFileAtomic(file: CerbosPolicyFile): Promise<void> {
    const target = join(this.policyDir, file.fileName);
    const tmp = `${target}.tmp-${String(process.pid)}-${String(Date.now())}`;
    const yaml = `${GENERATED_BANNER}${serialize(file.document)}`;
    await writeFile(tmp, yaml, 'utf8');
    await rename(tmp, target);
  }
}

/** Deterministic YAML serialization (stable key ordering off so Cerbos schema order). */
function serialize(document: CerbosPolicyDocument): string {
  return yamlDump(document, { lineWidth: 120, noRefs: true });
}
